// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    PluginAction,
    PluginActionField,
    PluginCapabilities,
    PluginPostExAction,
    PluginSnapshot
} from "./models.js";

import * as $models from "./models.js";

/**
 * LocalizedText 支持两种声明形式:
 *   - 字符串:   "Whoami"                (单一语言文案)
 *   - 对象:     {"zh": "...", "en": "..."}
 * 
 * 内部统一为 map[string]string; 纯字符串形式存入 "default" 键。
 * MarshalJSON 时若只有 default 键则回写为字符串, 保持快照紧凑。
 * @typedef {$models.LocalizedText} LocalizedText
 */
