// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as args$0 from "../args/models.js";

/**
 * LocalizedText 支持两种声明形式:
 *   - 字符串:   "Whoami"                (单一语言文案)
 *   - 对象:     {"zh": "...", "en": "..."}
 * 
 * 内部统一为 map[string]string; 纯字符串形式存入 "default" 键。
 * MarshalJSON 时若只有 default 键则回写为字符串, 保持快照紧凑。
 * @typedef {any} LocalizedText
 */

export class PluginAction {
    /**
     * Creates a new PluginAction instance.
     * @param {Partial<PluginAction>} [$$source = {}] - The source object to create the PluginAction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["kind"] = undefined;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["label"] = null;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["description"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["os"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["arch"] = undefined;
        }
        if (!("artifact" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifact"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["artifact_by_arch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["artifact_data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PluginPostExAction | null | undefined}
             */
            this["postex"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Module 指向 PostEx module manifest(beacon.postex.module/v1)。
             * schema v2: postex 动作的配置与字段从 module manifest 派生, postex 块仅作 override。
             * @member
             * @type {string | undefined}
             */
            this["module"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["command_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * RequiresInput 仅作显式覆盖: false(零值)时省略该键,
             * 前端按 v2 约定回退为"有字段即需要输入"(requiresInput = fields.length > 0)。
             * @member
             * @type {boolean | undefined}
             */
            this["requires_input"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PluginActionField[] | undefined}
             */
            this["fields"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {args$0.BeaconCommandArg[] | undefined}
             */
            this["args"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginAction}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("os" in $$parsedSource) {
            $$parsedSource["os"] = $$createField4_0($$parsedSource["os"]);
        }
        if ("arch" in $$parsedSource) {
            $$parsedSource["arch"] = $$createField5_0($$parsedSource["arch"]);
        }
        if ("artifact_by_arch" in $$parsedSource) {
            $$parsedSource["artifact_by_arch"] = $$createField7_0($$parsedSource["artifact_by_arch"]);
        }
        if ("postex" in $$parsedSource) {
            $$parsedSource["postex"] = $$createField9_0($$parsedSource["postex"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField13_0($$parsedSource["fields"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField14_0($$parsedSource["args"]);
        }
        return new PluginAction(/** @type {Partial<PluginAction>} */($$parsedSource));
    }
}

export class PluginActionField {
    /**
     * Creates a new PluginActionField instance.
     * @param {Partial<PluginActionField>} [$$source = {}] - The source object to create the PluginActionField.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["label"] = null;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["default"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["default_by_arch"] = undefined;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("help" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["help"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["role"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["postex_arg"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginActionField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginActionField}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType8;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default_by_arch" in $$parsedSource) {
            $$parsedSource["default_by_arch"] = $$createField5_0($$parsedSource["default_by_arch"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new PluginActionField(/** @type {Partial<PluginActionField>} */($$parsedSource));
    }
}

/**
 * PluginCapabilities 声明插件允许投递的 Beacon 命令白名单。
 * schema v2 必填: dispatch 前校验最终 command_id 必须落在 CommandIDs 内。
 */
export class PluginCapabilities {
    /**
     * Creates a new PluginCapabilities instance.
     * @param {Partial<PluginCapabilities>} [$$source = {}] - The source object to create the PluginCapabilities.
     */
    constructor($$source = {}) {
        if (!("command_ids" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["command_ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginCapabilities instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginCapabilities}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command_ids" in $$parsedSource) {
            $$parsedSource["command_ids"] = $$createField0_0($$parsedSource["command_ids"]);
        }
        return new PluginCapabilities(/** @type {Partial<PluginCapabilities>} */($$parsedSource));
    }
}

export class PluginPostExAction {
    /**
     * Creates a new PluginPostExAction instance.
     * @param {Partial<PluginPostExAction>} [$$source = {}] - The source object to create the PluginPostExAction.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dll"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["dll_by_arch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["manifest"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["wait_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["max_runtime_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["idle_timeout_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["module_args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["spawn_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["spawn_path_by_arch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["spawn_args"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginPostExAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginPostExAction}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dll_by_arch" in $$parsedSource) {
            $$parsedSource["dll_by_arch"] = $$createField2_0($$parsedSource["dll_by_arch"]);
        }
        if ("spawn_path_by_arch" in $$parsedSource) {
            $$parsedSource["spawn_path_by_arch"] = $$createField10_0($$parsedSource["spawn_path_by_arch"]);
        }
        return new PluginPostExAction(/** @type {Partial<PluginPostExAction>} */($$parsedSource));
    }
}

/**
 * PluginSnapshot 用于向前端同步插件的当前状态快照
 */
export class PluginSnapshot {
    /**
     * Creates a new PluginSnapshot instance.
     * @param {Partial<PluginSnapshot>} [$$source = {}] - The source object to create the PluginSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["display_name"] = null;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {LocalizedText}
             */
            this["description"] = null;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("capabilities" in $$source)) {
            /**
             * @member
             * @type {PluginCapabilities | null}
             */
            this["capabilities"] = null;
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {PluginAction[]}
             */
            this["actions"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * loading, ready, error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error"] = "";
        }
        if (!("loaded_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loaded_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType11;
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField6_0($$parsedSource["capabilities"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new PluginSnapshot(/** @type {Partial<PluginSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = PluginPostExAction.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = PluginActionField.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = args$0.BeaconCommandArg.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = PluginCapabilities.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = PluginAction.createFrom;
const $$createType13 = $Create.Array($$createType12);
