// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService is a service for reading the local filesystem
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ReadBinaryFileBase64 reads a local file and returns base64-encoded data
 * @param {string} sourcePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadBinaryFileBase64(sourcePath) {
    return $Call.ByID(1464573290, sourcePath);
}

/**
 * WriteBinaryFile decodes base64 data and writes it to the specified local path
 * @param {string} targetPath
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function WriteBinaryFile(targetPath, base64Data) {
    return $Call.ByID(640552146, targetPath, base64Data);
}
