// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class BeaconCommandArg {
    /**
     * Creates a new BeaconCommandArg instance.
     * @param {Partial<BeaconCommandArg>} [$$source = {}] - The source object to create the BeaconCommandArg.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BeaconCommandArg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BeaconCommandArg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BeaconCommandArg(/** @type {Partial<BeaconCommandArg>} */($$parsedSource));
    }
}

export class PluginAction {
    /**
     * Creates a new PluginAction instance.
     * @param {Partial<PluginAction>} [$$source = {}] - The source object to create the PluginAction.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["os"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["arch"] = undefined;
        }
        if (!("artifact" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifact"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_: string]: string } | undefined}
             */
            this["artifact_by_arch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["artifact_data"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["command_id"] = undefined;
        }
        if (!("requires_input" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requires_input"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PluginActionField[] | undefined}
             */
            this["fields"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BeaconCommandArg[] | undefined}
             */
            this["args"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginAction}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("os" in $$parsedSource) {
            $$parsedSource["os"] = $$createField3_0($$parsedSource["os"]);
        }
        if ("arch" in $$parsedSource) {
            $$parsedSource["arch"] = $$createField4_0($$parsedSource["arch"]);
        }
        if ("artifact_by_arch" in $$parsedSource) {
            $$parsedSource["artifact_by_arch"] = $$createField6_0($$parsedSource["artifact_by_arch"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField10_0($$parsedSource["fields"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField11_0($$parsedSource["args"]);
        }
        return new PluginAction(/** @type {Partial<PluginAction>} */($$parsedSource));
    }
}

export class PluginActionField {
    /**
     * Creates a new PluginActionField instance.
     * @param {Partial<PluginActionField>} [$$source = {}] - The source object to create the PluginActionField.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["default"] = null;
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["required"] = false;
        }
        if (!("help" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["help"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginActionField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginActionField}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        return new PluginActionField(/** @type {Partial<PluginActionField>} */($$parsedSource));
    }
}

/**
 * PluginSnapshot 用于向前端同步插件的当前状态快照
 */
export class PluginSnapshot {
    /**
     * Creates a new PluginSnapshot instance.
     * @param {Partial<PluginSnapshot>} [$$source = {}] - The source object to create the PluginSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("permissions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["permissions"] = [];
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {PluginAction[]}
             */
            this["actions"] = [];
        }
        if (!("status" in $$source)) {
            /**
             * loading, ready, error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("last_error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_error"] = "";
        }
        if (!("loaded_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["loaded_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField6_0($$parsedSource["permissions"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField7_0($$parsedSource["actions"]);
        }
        return new PluginSnapshot(/** @type {Partial<PluginSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = PluginActionField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = BeaconCommandArg.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PluginAction.createFrom;
const $$createType7 = $Create.Array($$createType6);
