// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} sourcePath
 * @returns {$CancellablePromise<$models.PluginSnapshot[]>}
 */
export function AddPlugin(sourcePath) {
    return $Call.ByID(573901041, sourcePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pluginID
 * @returns {$CancellablePromise<$models.PluginSnapshot[]>}
 */
export function DeletePlugin(pluginID) {
    return $Call.ByID(2934088899, pluginID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pluginID
 * @returns {$CancellablePromise<$models.PluginSnapshot>}
 */
export function GetPlugin(pluginID) {
    return $Call.ByID(3706531778, pluginID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} pluginID
 * @param {string} action
 * @param {string} payloadJSON
 * @returns {$CancellablePromise<$models.PluginSnapshot>}
 */
export function InvokePluginAction(pluginID, action, payloadJSON) {
    return $Call.ByID(2413106546, pluginID, action, payloadJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PluginSnapshot[]>}
 */
export function ListPlugins() {
    return $Call.ByID(936869721).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PluginSnapshot[]>}
 */
export function ReloadPlugins() {
    return $Call.ByID(1463169090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.PluginSnapshot.createFrom;
const $$createType1 = $Create.Array($$createType0);
