// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * *
 *  * ProxyService
 *  * 职责：代理前端请求，绕开浏览器 CORS 限制与 TLS 证书验证
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * *
 *  * DoRequest 执行转发请求
 *  * @param method HTTP 方法 (GET, POST, etc.)
 *  * @param url 完整的请求地址
 *  * @param payload JSON 报文体
 *  * @param headersMap 头信息映射
 * @param {string} method
 * @param {string} url
 * @param {string} payload
 * @param {{ [_: string]: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function DoRequest(method, url, payload, headersMap) {
    return $Call.ByID(3950893472, method, url, payload, headersMap);
}

/**
 * @param {string} url
 * @param {{ [_: string]: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFileBase64(url, headersMap) {
    return $Call.ByID(2306400731, url, headersMap);
}

/**
 * @param {string} url
 * @param {string} fileName
 * @param {string} base64Data
 * @param {{ [_: string]: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function UploadFileBase64(url, fileName, base64Data, headersMap) {
    return $Call.ByID(157469278, url, fileName, base64Data, headersMap);
}
