// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} apiBase
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function Connect(apiBase, token) {
    return $Call.ByID(154642053, apiBase, token);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(2994002663);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Status() {
    return $Call.ByID(2449699251);
}
