// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 内嵌 internal/file.FileService 的指针,获得其全部 Wails 方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ReadBinaryFileBase64 reads a local file and returns base64-encoded data.
 * 
 * Files larger than 50MB are rejected — use ReadBinaryFileBase64Chunked instead
 * to avoid loading the entire file into memory.
 * @param {string} sourcePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadBinaryFileBase64(sourcePath) {
    return $Call.ByID(3032372772, sourcePath);
}

/**
 * ReadBinaryFileBase64Chunked reads a local file in chunks and returns
 * base64-encoded chunks with their offsets. This is for large files that
 * exceed the 50MB single-read limit.
 * 
 * Returns a JSON array of [{offset, total_size, chunk_size, base64_data}].
 * The caller can iterate chunks and concatenate decoded data.
 * @param {string} sourcePath
 * @param {number} chunkSize
 * @returns {$CancellablePromise<string>}
 */
export function ReadBinaryFileBase64Chunked(sourcePath, chunkSize) {
    return $Call.ByID(2872445472, sourcePath, chunkSize);
}

/**
 * WriteBinaryFile decodes base64 data and writes it to the specified local path.
 * 
 * The path is normalized and checked for directory traversal attacks.
 * Existing files are overwritten only if the user has write permission.
 * @param {string} targetPath
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function WriteBinaryFile(targetPath, base64Data) {
    return $Call.ByID(2214284272, targetPath, base64Data);
}
