// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService 内嵌 internal/plugin.PluginService 的指针,获得其全部 Wails 方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "./internal/plugin/models.js";

/**
 * @param {string} sourcePath
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot[]>}
 */
export function AddPlugin(sourcePath) {
    return $Call.ByID(2588414803, sourcePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pluginID
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot[]>}
 */
export function DeletePlugin(pluginID) {
    return $Call.ByID(1318120297, pluginID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pluginID
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot>}
 */
export function GetPlugin(pluginID) {
    return $Call.ByID(815439216, pluginID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} pluginID
 * @param {string} action
 * @param {string} payloadJSON
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot>}
 */
export function InvokePluginAction(pluginID, action, payloadJSON) {
    return $Call.ByID(3829653372, pluginID, action, payloadJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot[]>}
 */
export function ListPlugins() {
    return $Call.ByID(3489214987).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<plugin$0.PluginSnapshot[]>}
 */
export function ReloadPlugins() {
    return $Call.ByID(3357754944).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = plugin$0.PluginSnapshot.createFrom;
const $$createType1 = $Create.Array($$createType0);
