// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService 内嵌 internal/transport.ProxyService 的指针,获得其全部 Wails 方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DoRequestWithStatus executes a forwarded request and returns a structured
 * JSON string containing the HTTP status code, response body, and optional error.
 * 
 * HTTP-level failures (4xx/5xx) never produce a Go error: everything is encoded
 * into ProxyResult so the frontend can handle status codes programmatically.
 * 
 * Network-level failures (DNS, connection refused, timeout) return status=0
 * with the error field populated. The Go error return is reserved for cases
 * where the method cannot produce a valid JSON response.
 * @param {string} method
 * @param {string} url
 * @param {string} payload
 * @param {{ [_ in string]?: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function DoRequestWithStatus(method, url, payload, headersMap) {
    return $Call.ByID(846269776, method, url, payload, headersMap);
}

/**
 * @param {string} url
 * @param {{ [_ in string]?: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFileBase64(url, headersMap) {
    return $Call.ByID(401467949, url, headersMap);
}

/**
 * @param {string} url
 * @param {string} fileName
 * @param {string} base64Data
 * @param {{ [_ in string]?: string }} headersMap
 * @returns {$CancellablePromise<string>}
 */
export function UploadFileBase64(url, fileName, base64Data, headersMap) {
    return $Call.ByID(1724571644, url, fileName, base64Data, headersMap);
}
