// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebSocketService 内嵌 internal/transport.WebSocketService 的指针,获得其全部 Wails 方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} apiBase
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function Connect(apiBase, token) {
    return $Call.ByID(2872531239, apiBase, token);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1811738041);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Status() {
    return $Call.ByID(741346597);
}
