// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BeaconCommandArg 是 beacon 命令的单个参数。
 * 放在本包因为 BuildBeaconCommandArg 等函数构造它,plugin 包通过 Args []BeaconCommandArg 引用。
 */
export class BeaconCommandArg {
    /**
     * Creates a new BeaconCommandArg instance.
     * @param {Partial<BeaconCommandArg>} [$$source = {}] - The source object to create the BeaconCommandArg.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BeaconCommandArg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BeaconCommandArg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BeaconCommandArg(/** @type {Partial<BeaconCommandArg>} */($$parsedSource));
    }
}
